title: B2C Solution Architect Program
logo: /assets/img/Solution_Architect_Program_B2C_Logo_Vert_RGB.png
description: Home for Assets Related to the B2C Solution Architect Program. 
show_downloads: false
google_analytics: UA-191200364-1
theme: jekyll-theme-minimal
